Done Homework Test_Lecture
Chepak-Semen/Python-Enchantress pull request #3
Opened 2021-01-14 12:14 UTC by Chepak-Semen

2021-01-14 12:27 UTC, Chepak-Semen commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#3-TestChepak-Semen](https://trello.com/c/7eCoJle1/60-hw3-testchepak-semen)

2021-01-15 14:48 UTC, oliaboo requested changes

2021-01-15 14:48 UTC, oliaboo commented on homework/Homework_Test.py
> +        self.assertRaises(ValueError, lambda: test_simple_calc.divide(2, 0))
separate test - test_divide_by_zero

2021-01-15 14:48 UTC, oliaboo commented on homework/Homework_Test.py
> +PERSON = tests_simple_employee.Employee('Andriy', 'Rocket', 10000)
move to either setUp or fixture (GLOBAL should not be widely used)

2021-01-15 14:48 UTC, oliaboo commented on homework/Homework_Test.py
> +            mock.return_value.ok = False
add test for ok response

2021-01-15 14:48 UTC, oliaboo commented on homework/Homework_test_2.py
> +        self.TESTER = Test()
`TESTER` - upper-case not needed

2021-01-15 14:48 UTC, oliaboo commented on homework/Homework_test_2.py
> +        self.m = mock.Mock()
`m` is a bad name, I should understand what for it stays from the name

2021-01-15 14:48 UTC, oliaboo commented on homework/Homework_test_2.py
> +            print(f"{self._testMethodName} Was Successful : {self.defaultTestResult().wasSuccessful()}")
did you thy making higher verbosity for unittest run?
not actually sure, this is needed.

2021-01-15 14:48 UTC, oliaboo commented on homework/Homework_test_2.py
> +        self.assertEqual(func(), 1)
as an idea:
you may mock `new_test` function with:
```
mock.MagicMock(
        __enter__=<enter_mock>,
        __exit__=<exit_mock>
    )
```
and then check whether `__enter__` and `__exit__` have been called

2021-01-15 14:50 UTC, oliaboo commented on homework/.gitignore
> +*.idea
https://github.com/github/gitignore/blob/master/Python.gitignore
here is the example for .gitignore file within Python project (at least, add `__pycache__`)

2021-01-19 14:17 UTC, dimigor requested changes

2021-01-19 14:17 UTC, dimigor commented on homework/Homework_Test.py
> +        self.assertRaises(ValueError, lambda: test_simple_calc.divide(2, 0))
Зроби два окремі тести, коли вдале ділення, і коли з ексепшином

2021-01-19 14:39 UTC, Chepak-Semen commented on homework/Homework_Test.py
> +        self.assertRaises(ValueError, lambda: test_simple_calc.divide(2, 0))
О'кей

2021-01-19 18:30 UTC, dimigor approved these changes

2021-01-19 18:31 UTC, merged