9HW. Try to solve with using blueprints and restful
Chepak-Semen/Python-Enchantress pull request #6
Opened 2021-02-12 18:39 UTC by Chepak-Semen

2021-02-12 18:45 UTC, Chepak-Semen commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#9 - Flask practice -Chepak Semen](https://trello.com/c/R4Bqi1o1/145-hw9-flask-practice-chepak-semen)

2021-02-14 17:53 UTC, dimigor requested changes

2021-02-14 17:53 UTC, dimigor commented on homework/flask/flask_hw_9/blueptints_user.py
> +        user = USERS_DATABASE[user_id]
краще використай метод .get

2021-02-14 17:53 UTC, dimigor commented on homework/flask/flask_hw_9/blueptints_user.py
> +        user = USERS_DATABASE[user_id]
він повертає Нан якщо нема ключа

2021-02-14 17:53 UTC, dimigor commented on homework/flask/flask_hw_9/blueptints_user.py
> +    except False or KeyError:
False це не ексепшин

2021-02-18 15:40 UTC, Chepak-Semen commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW#09-Chepak Semen](https://trello.com/c/7wwiU3d6/157-hw09-chepak-semen)

2021-02-18 15:47 UTC, merged